# Site settings
title: First steps  
subtitle: by HTML5 UP
email: bedratyy@gmail.com
description: test
baseurl: "curly-more/" # the subpath of your site, e.g. /blog
url: "https://bedratyy.gitlab.io" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: 
state: 
zip_code: 
country: Russia
phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
  style: compressed
